### ISSUE TITLE
UnhashableTypeError: Cannot hash object of type tokenizers.Tokenizer

### ISSUE THREAD

**Issue by mkhvalchik** [mihail911/question-answering-with-streamlit#2] opened 2020-11-30 20:29 UTC
Facing a hashing error on macOS Big Sur with M1 chip. Previously on i5 there was no such error.
python 3.8.5
streamlit 0.71.0
torch 1.7.0
transformers 4.1.0

<img width="720" alt="Screen Shot 2020-11-30 at 12 16 34 PM" src="https://user-images.githubusercontent.com/14086121/100659802-f7317a00-3305-11eb-9021-2eca2942d993.png">

**Comment by mihail911** [comment] 2020-12-05 07:03
That's bizarre. I haven't seen a reported error for this on the Streamlit repo, but I have heard of the M1 chips causing problems in other libraries. If you want to take a look at fixing this, that would be helpful!

**Comment by migalkin** [comment] 2021-01-07 18:06
Not sure if tackling the issue still makes sense, but I managed to solve it - apparently the issue is in the Rust-compiled `tokenizers`. I have an M1 MBP.

1. Installed native M1 rust compiler from [here](https://www.rust-lang.org/tools/install)
2. Started the terminal in the Rosetta mode (so that torch and everything else installs in the x86-compatible mode) and installed all dependencies of this project
3. `pip uninstall tokenizers` - to delete the fetched x86 one
4. And then build tokenizers from sources as described in the [doc](https://huggingface.co/docs/tokenizers/python/latest/installation/main.html)

The pipeline works :)

**Comment by mihail911** [comment] 2021-01-08 08:30
Thanks for the fix @migalkin! I'll close the issue for now.

**Closed as completed by mihail911** 2021-01-08 08:30 UTC
